server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # USER-SERVICE
        - id: user-service-auth
          uri: http://192.168.5.105:9000
          predicates:
            - Path=/api/auth/**

        - id: user-service-manager
          uri: http://192.168.5.105:9000
          predicates:
            - Path=/api/manager/**
        # PRODUCT-SERVICE
        - id: product-categories
          uri: http://192.168.5.105:9001
          predicates:
            - Path=/api/categories/**

        - id: product-products
          uri: http://192.168.5.105:9001
          predicates:
            - Path=/api/products/**

        - id: product-admin
          uri: http://192.168.5.105:9001
          predicates:
            - Path=/admin/products/**

        # ORDER-SERVICE
        - id: order-service-carts
          uri: http://192.168.5.105:9002
          predicates:
            - Path=/api/cart/**

        - id: order-service-orders
          uri: http://192.168.5.105:9002
          predicates:
            - Path=/api/order/**
